name: unflutterraid
description: A Flutter implementation of the Unraid mobile prototype pages.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  connectivity_plus: ^7.3.0
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^10.3.1
  http: ^1.2.2
  intl: ^0.20.2
  just_audio: ^0.10.6
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  package_info_plus: ^9.0.1
  pdfrx: ^2.4.7
  permission_handler: ^11.3.1
  photo_manager: ^3.10.0
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
